### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'daemon' in Python 2.7.13

### ISSUE THREAD

**Issue by maneeshd** [ranaroussi/multitasking#1]
Hi,

Getting this exception when multitasking.task is run

> Traceback (most recent call last):
File "C:/Users/mdivana/PythonProjects/Get Platform Details FlaskApp/wonder.py", line 16, in <module> 
    run()
File "C:\Users\mdivana\AppData\Local\Continuum\Anaconda3\envs\py27\lib\site-packages\multitasking\__init__.py", line 107, in async_method
    target=_run_via_pool, args=args, kwargs=kwargs, daemon=False)
TypeError: __init__() got an unexpected keyword argument 'daemon'

This is the code I ran:

```python
import multitasking

@multitasking.task
def run():
    print("Yes!")

if __name__ == '__main__':
    for i in range(5):
        run()
    print("Hello")
```

Python: 2.7.13
multitasking: 0.0.4
OS: Windows 10

Thanks

**Comment by khrlimam** [comment]
Got same error here :hand:

**Comment by khrlimam** [comment]
you can check my commit here [remove daemon argument](https://github.com/ranaroussi/multitasking/pull/2/commits/059ccaa05f00874157d1f17d96a391fb3d789ff7).
