### ISSUE TITLE
Ctrl+C

### ISSUE THREAD

**Issue by creeper6530** [ranaroussi/multitasking#18]
Hey,
I used a sample code from README, and edited it a bit. Here's the result:
```python

import multitasking
import time
import random
import signal

@multitasking.task
def hello(count):
    sleep = random.randint(1,10)/2
    print("Hello %s (sleeping for %ss)" % (count, sleep))
    time.sleep(sleep)
    print("Goodbye %s (after for %ss)" % (count, sleep))

for i in range(0, 10):
    hello(i+1)
input()
```

And here's the problem: I cannot use Ctrl+C to immediately stop every single task.

Can you help me, please?

P.S.: Please forgive me if I have done some stupid mistake.

**Comment by datatalking** [comment]
So if I understand the issue, you want to manually stop them all at once via the keyboard, but don't want to do it programmatically? (in your code)

What is your use case for doing via the keyboard, is this just a functionality test or?

I recreated your code and found it working

```
(base) users-iMac:test userwilson$ python3 test_code_multitasking.py 
Hello 1 (sleeping for 2.5s)
Hello 2 (sleeping for 2.5s)
Hello 3 (sleeping for 2.5s)
Hello 4 (sleeping for 4.0s)
Goodbye 1 (after for 2.5s)
Goodbye 2 (after for 2.5s)
Goodbye 3 (after for 2.5s)
Hello 6 (sleeping for 4.5s)
Hello 5 (sleeping for 2.0s)
Hello 7 (sleeping for 0.5s)
Goodbye 7 (after for 0.5s)
Hello 8 (sleeping for 3.5s)
Goodbye 4 (after for 4.0s)
Hello 9 (sleeping for 3.5s)
Goodbye 5 (after for 2.0s)
Hello 10 (sleeping for 1.0s)
Goodbye 10 (after for 1.0s)
Goodbye 8 (after for 3.5s)
Goodbye 6 (after for 4.5s)
^CTraceback (most recent call last):
  File "test_code_multitasking.py", line 15, in <module>
    input()
KeyboardInterrupt
Goodbye 9 (after for 3.5s)
```

**Comment by creeper6530** [comment]
It didn't work with the same code. Output:

```
~ $ python tmp.py
Hello 1 (sleeping for 2.5s)
Hello 2 (sleeping for 1.5s)
Hello 3 (sleeping for 1.0s)
Hello 4 (sleeping for 3.5s)
Hello 5 (sleeping for 0.5s)
Hello 6 (sleeping for 4.0s)
Hello 7 (sleeping for 3.0s)
Hello 8 (sleeping for 1.5s)
Goodbye 5 (after for 0.5s)
Hello 9 (sleeping for 2.0s)
Goodbye 3 (after for 1.0s)
Hello 10 (sleeping for 3.0s)
^C
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tmp.py", line 16, in <module>
    input()
KeyboardInterrupt
Goodbye 2 (after for 1.5s)
Goodbye 8 (after for 1.5s)
Goodbye 1 (after for 2.5s)
Goodbye 9 (after for 2.0s)
Goodbye 7 (after for 3.0s)
Goodbye 4 (after for 3.5s)
Goodbye 6 (after for 4.0s)
Goodbye 10 (after for 3.0s)
```

I want to be able to exit program completely.

**Comment by datatalking** [comment]
@creeper6530 are you by chance on a windows machine?

I'm unable to reproduce your error from my end.

**Comment by datatalking** [comment]
@creeper6530 ok, it looks like this is a known issue with Windows. The Python core dev people seem to have it on their to-do list since 2019. You could set up a Linux terminal inside a VM ware box or now might be an opportune time to learn docker.

Known Bug https://bugs.python.org/issue38428

**Comment by creeper6530** [comment]
OK, I'll try. By default, I'm on Windows 10 with ability to use VirtualBox and WSL. I can also use Termux on Android. I will test it on every platform I can. After tests, I will post every output I will get with corresponding platform.

**Comment by creeper6530** [comment]
Windows 10:
```python
C:\Users\Admin\Desktop>C:/Users/Admin/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Admin/Desktop/tmp.py
Hello 1 (sleeping for 1.5s)
Hello 2 (sleeping for 5.0s)
Hello 3 (sleeping for 2.5s)
Hello 4 (sleeping for 2.5s)
Hello 5 (sleeping for 3.0s)
Hello 6 (sleeping for 2.5s)
Hello 7 (sleeping for 1.5s)
Hello 8 (sleeping for 1.5s)
Goodbye 1 (after for 1.5s)
Hello 9 (sleeping for 3.0s)
Goodbye 8 (after for 1.5s)
Goodbye 7 (after for 1.5s)
Hello 10 (sleeping for 1.0s)
Goodbye 3 (after for 2.5s)
Goodbye 6 (after for 2.5s)
Goodbye 4 (after for 2.5s)
Goodbye 10 (after for 1.0s)
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\tmp.py", line 16, in <module>
    input()
KeyboardInterrupt
Goodbye 5 (after for 3.0s)
Goodbye 9 (after for 3.0s)
Goodbye 2 (after for 5.0s)
^C
```
VirtualBox VM: _was unable to use - could not install VM_
WSL: _was unable to use - PyPI has not been working -> could not run code_
Termux:
```python
~ $ python tmp.py
Hello 1 (sleeping for 0.5s)
Hello 2 (sleeping for 4.5s)
Hello 3 (sleeping for 1.0s)
Hello 4 (sleeping for 3.5s)
Hello 5 (sleeping for 0.5s)
Hello 6 (sleeping for 0.5s)
Hello 7 (sleeping for 5.0s)
Hello 8 (sleeping for 2.0s)
Goodbye 1 (after for 0.5s)
Hello 9 (sleeping for 0.5s)
Goodbye 5 (after for 0.5s)
Hello 10 (sleeping for 1.5s)
Goodbye 6 (after for 0.5s)
Goodbye 9 (after for 0.5s)
Goodbye 3 (after for 1.0s)
^C
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tmp.py", line 16, in <module>
    input()
KeyboardInterrupt
Goodbye 10 (after for 1.5s)
Goodbye 8 (after for 2.0s)
Goodbye 4 (after for 3.5s)
Goodbye 2 (after for 4.5s)
Goodbye 7 (after for 5.0s)
```

A bit late: Reason why I am asking: I've got bigger project that uses multitasking library for (obviously) multitasking (specifically send and recieve UDP packets at same time) and I cannot stop it by Ctrl+C. That is a big problem for me.
I used sample code from README for reproducing.

**Comment by creeper6530** [comment]
> So if I understand the issue, you want to manually stop them all at once via the keyboard, but don't want to do it programmatically? (in your code)
> 
> What is your use case for doing via the keyboard, is this just a functionality test or?
> 
> I recreated your code and found it working
> 
> ```
> (base) users-iMac:test userwilson$ python3 test_code_multitasking.py 
> Hello 1 (sleeping for 2.5s)
> Hello 2 (sleeping for 2.5s)
> Hello 3 (sleeping for 2.5s)
> Hello 4 (sleeping for 4.0s)
> Goodbye 1 (after for 2.5s)
> Goodbye 2 (after for 2.5s)
> Goodbye 3 (after for 2.5s)
> Hello 6 (sleeping for 4.5s)
> Hello 5 (sleeping for 2.0s)
> Hello 7 (sleeping for 0.5s)
> Goodbye 7 (after for 0.5s)
> Hello 8 (sleeping for 3.5s)
> Goodbye 4 (after for 4.0s)
> Hello 9 (sleeping for 3.5s)
> Goodbye 5 (after for 2.0s)
> Hello 10 (sleeping for 1.0s)
> Goodbye 10 (after for 1.0s)
> Goodbye 8 (after for 3.5s)
> Goodbye 6 (after for 4.5s)
> ^CTraceback (most recent call last):
>   File "test_code_multitasking.py", line 15, in <module>
>     input()
> KeyboardInterrupt
> Goodbye 9 (after for 3.5s)
> ```

btw, your recreation didn't work: even after `KeyboardInterrupt`, the program was going on, indicated by `Goodbye 9`. After `KeyboardInterrupt`, it should halt and do nothing, but it continued.

**Comment by datatalking** [comment]
@creeper6530 I think we have a failure to read the docs... if I understand your question. This is most likely a Windows issue. You need to call Bill Gates and tell him to hire software developers to solve the issue. This is a reason like 12,384 that the world left Microsoft .NET, VBA, and everything they make in the dust and moved most software development to Linux.

Virtual box is certainly one option, but then you are running a Windows environment and starting a Linux environment inside that you are creating more problems. That way leads to madness, sadness, and hours pounding your head against the desk. Put down the Windows software and back away from Microsoft.

You need to load a separate container or volume on your base hard drive and create a separate Linux install, also called dual boot. Develop it from there. The alternate option is to buy a mac and use that as your standard actual Unix environment like 88% of software engineers and data scientists use.

Known Bug https://bugs.python.org/issue38428

**Comment by creeper6530** [comment]
OK, I'll try your tip. Just by the way, I use Windows for development because I share the .exe bundles to my non-programmer friends and I need to know how it will behave on their devices.

Thank you for all your help. Hope I'll be able to help you back sometime.
