### ISSUE TITLE
a bug when i want to use multitasking twice

### ISSUE THREAD

**Issue by LogicJake** [ranaroussi/multitasking#5]
Thanks for your great work.
But when i want to use multitasking twice, it does not work as expected at the second time. If you want to  reproduce the bug, you can run the following code.
```
import multitasking
import signal
multitasking.set_max_threads()
multitasking.set_engine("process")
signal.signal(signal.SIGINT, multitasking.killall)


@multitasking.task
def task1():
    print(1)


@multitasking.task
def task2():
    print(2)


if __name__ == '__main__':
    for i in range(3):
        task1()

    multitasking.wait_for_tasks()
    # multitasking.config["KILL_RECEIVED"] = False

    for i in range(3):
        task2()
    multitasking.wait_for_tasks()

```
After reading your code, it seems that config["KILL_RECEIVED"] prevents adding new task into the pool  because the value of config["KILL_RECEIVED"] is True.

So the problem is that after using wait_for_tasks, you can not add new task because of config["KILL_RECEIVED"]. Now I just add 'config["KILL_RECEIVED"] = False' after wait_for_tasks to avoid this bug.

**Comment by ranaroussi** [comment]
why do you have ``multitasking.wait_for_tasks()`` in the code? It's unnecessary...

**Comment by LogicJake** [comment]
> why do you have `multitasking.wait_for_tasks()` in the code? It's unnecessary...

Thank you for your response. My program is divided into two parts, and the second part depends on the results of the first part. If I don't use `multitasking.wait_for_tasks()`, it will run the second part directly after starting the first part.

**Comment by ranaroussi** [comment]
Got it! I've updated the code to set ``config["KILL_RECEIVED"]`` to ``False`` once ``wait_for_tasks()`` finish running.

**Comment by LogicJake** [comment]
> Got it! I've updated the code to set `config["KILL_RECEIVED"]` to `False` once `wait_for_tasks()` finish running.

Thank you!!!
