### ISSUE TITLE
Using Processes Rather than Threads Doesn't Work as Documented + Workaround

### ISSUE THREAD

**Issue by bcbrock** [ranaroussi/multitasking#6]
Hi Ran,

Thank you for publishing this package.

The issue is that the documented method to use processes rather than threads:
```
import multitasking
multitasking.set_engine("process") # "process" or "thread"
```
does not work. I don't believe that the `set_engine` call has any effect at all on the behavior of the package. This is because `createPool` always overwrites the "ENGINE" from it's parameter (defaulting to 'thread').

For others having this issue, a simple workaround is to create a default pool explicitly:
```
import multitasking
multitasking.createPool(engine='process')
```

Thanks,

Bishop Brock

**Comment by ranaroussi** [comment]
fixed in v 0.0.8 :)
