### ISSUE TITLE
Feature Request: Enable multiple joins

### ISSUE THREAD

**Issue by bcbrock** [ranaroussi/multitasking#9]
Hi Ran,

I am using this package in scripts where I need to spawn some work, wait for it to complete, then spawn more work, wait, etc. etc. The issue is that the join method wait_for_tasks() is one-shot, because it keeps config["KILL_RECEIVED"]=True after the join completes, and when config["KILL_RECEIVED"] is True, task() is a NOP. Would you consider changing wait_for_tasks()  to enable multiple joins()? Also, to me not would be good for task() to throw an exception if it is called while a join is pending rather than silently doing nothing.

Thanks,

Bishop Brock

**Comment by ranaroussi** [comment]
Got it! This is a similar issue as #5... In any case - I've updated the code to set ``config["KILL_RECEIVED"]`` to ``False`` once ``wait_for_tasks()`` finish running.

**Comment by bcbrock** [comment]
Thank you.
